-- 0007_telegram_pairing_tokens.sql
--
-- Short-lived tokens that bridge `surge telegram setup` (which prints a
-- one-time pairing code) to `/pair <token>` inside Telegram (which exchanges
-- the token for a paired chat-id allowlist row — see 0008).
--
-- Tokens are 6-char Crockford base32, generated by surge-persistence's
-- pairing module. The (token, INSERT OR IGNORE) flow guarantees uniqueness
-- without a separate lock; on the rare collision the minter retries up to
-- a small number of attempts before surfacing an error.
--
-- consumed_at is NULL while the token is still valid. Once a chat consumes
-- it (becomes paired), consumed_at is set to the consumption timestamp so
-- the same token cannot be replayed. expires_at is checked at consume time;
-- expired tokens are rejected without being consumed so the row can be
-- garbage-collected later by a maintenance job.

CREATE TABLE IF NOT EXISTS telegram_pairing_tokens (
    token       TEXT    PRIMARY KEY,
    created_at  INTEGER NOT NULL,    -- Unix epoch ms
    expires_at  INTEGER NOT NULL,    -- Unix epoch ms
    consumed_at INTEGER,             -- Unix epoch ms; NULL while live
    label       TEXT                 -- operator-supplied chat label
);

CREATE INDEX IF NOT EXISTS idx_telegram_pairing_tokens_live
    ON telegram_pairing_tokens(expires_at)
    WHERE consumed_at IS NULL;
