//! `surge migrate-spec` CLI handler.
//!
//! Reads a legacy `.spec.toml` (via the deprecated [`surge_spec::SpecFile`]
//! parser — this is the only surviving direct caller during the retirement
//! window) and emits a `flow.toml` document built by [`super::mapping`].
//!
//! Exit codes:
//! - `0` — clean migration with no warnings, or warnings but `--allow-warnings`.
//! - `1` — parse / IO failure (propagated via `anyhow`).
//! - `2` — migration produced warnings and `--allow-warnings` was absent.

use std::fs;
use std::io::Write as _;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Args;
use tracing::{debug, info, warn};

use super::mapping::{MappingResult, MappingWarning, map_spec_to_flow};
use crate::legacy_spec::LegacySpecFile;

const EXIT_CODE_WARNINGS: i32 = 2;

/// CLI args for `surge migrate-spec <input> [--output] [--allow-warnings]`.
#[derive(Args, Debug)]
pub struct MigrateSpecArgs {
    /// Path to the legacy `.spec.toml` file to convert.
    pub input: PathBuf,

    /// Output `flow.toml` path. Defaults to stdout.
    #[arg(short = 'o', long)]
    pub output: Option<PathBuf>,

    /// Exit 0 even when the migration produces warnings.
    #[arg(long)]
    pub allow_warnings: bool,
}

/// Execute the `migrate-spec` command.
///
/// # Errors
///
/// - Input path cannot be read or parsed as a legacy spec.
/// - Mapping rejects the spec (cycle, empty, dangling deps).
/// - Output path cannot be written.
///
/// On warnings without `--allow-warnings`, the function still writes the
/// document and then terminates with exit code 2 via `std::process::exit`.
pub fn run(args: MigrateSpecArgs) -> Result<()> {
    info!(
        input = %args.input.display(),
        output = ?args.output.as_ref().map(|p| p.display().to_string()),
        allow_warnings = args.allow_warnings,
        "migrate-spec starting",
    );

    let spec_file = load_legacy_spec(&args.input)?;
    debug!(subtasks = spec_file.spec.subtasks.len(), "loaded spec");

    let result = map_spec_to_flow(&spec_file.spec)
        .with_context(|| format!("migrate-spec: mapping failed for {}", args.input.display()))?;

    let rendered = render_document(&result);
    write_output(&rendered, args.output.as_ref())?;
    report_warnings(&result.warnings);

    info!(warnings = result.warnings.len(), "migrate-spec finished",);

    if !result.warnings.is_empty() && !args.allow_warnings {
        warn!(
            warnings = result.warnings.len(),
            "exiting with status {EXIT_CODE_WARNINGS} because --allow-warnings was not set",
        );
        std::process::exit(EXIT_CODE_WARNINGS);
    }

    Ok(())
}

fn load_legacy_spec(path: &std::path::Path) -> Result<LegacySpecFile> {
    LegacySpecFile::load(path).with_context(|| {
        format!(
            "migrate-spec: failed to read legacy spec at {}",
            path.display()
        )
    })
}

fn render_document(result: &MappingResult) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(
        "# Generated by `surge migrate-spec`. Review the file before running.\n# \
         Spec→flow mapping reference: docs/migrate-spec-to-flow.md\n\n",
    );
    if !result.warnings.is_empty() {
        out.push_str("# Warnings raised during migration:\n");
        for w in &result.warnings {
            out.push_str("# - ");
            out.push_str(&w.message);
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str(&result.document.to_string());
    out
}

fn write_output(rendered: &str, output: Option<&PathBuf>) -> Result<()> {
    match output {
        Some(path) => {
            if let Some(parent) = path.parent() {
                if !parent.as_os_str().is_empty() {
                    fs::create_dir_all(parent).with_context(|| {
                        format!("migrate-spec: failed to create {}", parent.display())
                    })?;
                }
            }
            fs::write(path, rendered)
                .with_context(|| format!("migrate-spec: failed to write {}", path.display()))?;
            info!(output = %path.display(), "wrote flow.toml");
            Ok(())
        },
        None => {
            let mut stdout = std::io::stdout().lock();
            stdout
                .write_all(rendered.as_bytes())
                .context("migrate-spec: failed to write to stdout")?;
            stdout.flush().ok();
            Ok(())
        },
    }
}

fn report_warnings(warnings: &[MappingWarning]) {
    for w in warnings {
        warn!(
            kind = ?w.kind,
            subtask = ?w.subtask,
            "migrate-spec: {}",
            w.message,
        );
    }
}
