//! `surge init` defaults and worktree placement.

use super::*;

/// Project initialization defaults used by first-run onboarding.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct InitConfig {
    /// Default sandbox mode assigned by generated onboarding flows.
    #[serde(default = "default_init_sandbox_default")]
    pub sandbox_default: SandboxMode,
    /// Where managed per-run worktrees should be placed.
    #[serde(default)]
    pub worktree_location: WorktreeLocationConfig,
    /// Base directory for custom/local managed worktree placement.
    #[serde(default = "default_worktree_root")]
    pub worktree_root: PathBuf,
    /// Default policy for approval-gated actions.
    #[serde(default)]
    pub approval_policy: ApprovalPolicy,
    /// Channels preferred for approvals and elevation prompts.
    #[serde(default = "default_approval_channels")]
    pub approval_channels: Vec<ApprovalChannelKind>,
    /// Stable project context file generated by `surge project describe`.
    #[serde(default = "default_project_context_path")]
    pub project_context_path: PathBuf,
    /// Whether new runs should seed `project_context` from `project_context_path`.
    #[serde(default = "default_true")]
    pub project_context_auto_seed: bool,
    /// Human-readable source that last initialized this config.
    #[serde(default = "default_init_created_by")]
    pub created_by: String,
}

impl Default for InitConfig {
    fn default() -> Self {
        Self {
            sandbox_default: default_init_sandbox_default(),
            worktree_location: WorktreeLocationConfig::default(),
            worktree_root: default_worktree_root(),
            approval_policy: ApprovalPolicy::default(),
            approval_channels: default_approval_channels(),
            project_context_path: default_project_context_path(),
            project_context_auto_seed: true,
            created_by: default_init_created_by(),
        }
    }
}

impl InitConfig {
    pub(super) fn validate(&self) -> Result<(), crate::SurgeError> {
        if self.worktree_root.as_os_str().is_empty() {
            return Err(crate::SurgeError::Config(
                "init.worktree_root must not be empty".to_string(),
            ));
        }
        if self.project_context_path.as_os_str().is_empty() {
            return Err(crate::SurgeError::Config(
                "init.project_context_path must not be empty".to_string(),
            ));
        }
        let mut seen = std::collections::BTreeSet::new();
        for channel in &self.approval_channels {
            if !seen.insert(channel.as_str()) {
                return Err(crate::SurgeError::Config(format!(
                    "init.approval_channels contains duplicate channel '{}'",
                    channel.as_str()
                )));
            }
        }
        Ok(())
    }
}

/// Worktree placement strategy encoded in `surge.toml`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum WorktreeLocationConfig {
    /// Place worktrees next to the repository under `.surge-worktrees/`.
    #[default]
    Sibling,
    /// Place worktrees under the user's global `~/.surge/runs/` directory.
    Central,
    /// Use `init.worktree_root` as the base directory.
    Custom,
}

fn default_init_sandbox_default() -> SandboxMode {
    SandboxMode::WorkspaceWrite
}

fn default_worktree_root() -> PathBuf {
    PathBuf::from(".surge-worktrees")
}

fn default_approval_channels() -> Vec<ApprovalChannelKind> {
    vec![ApprovalChannelKind::Desktop]
}

fn default_project_context_path() -> PathBuf {
    PathBuf::from("project.md")
}

fn default_init_created_by() -> String {
    "surge init".to_string()
}
