//! Surge configuration.

use crate::approvals::{ApprovalChannelKind, ApprovalPolicy};
use crate::capacity_config::CapacityConfig;
use crate::context_pack::ContextPackConfig;
use crate::loop_config::ToolCallLoopGuardConfig;
use crate::mcp_config::McpServerRef;
use crate::sandbox::SandboxMode;
use crate::spill_config::OutputSpillConfig;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

fn default_default_agent() -> String {
    "claude-acp".to_string()
}

/// Current `surge.toml` schema version. Frozen at `1` for v0.1; bump only
/// alongside a documented migration (see `docs/schema-versioning.md`).
pub const CONFIG_SCHEMA_VERSION: u32 = 1;

fn default_config_schema_version() -> u32 {
    CONFIG_SCHEMA_VERSION
}

/// Top-level Surge configuration, loaded from `surge.toml`.
///
/// Controls agent routing, pipeline behaviour, resilience policies,
/// cleanup strategy, and analytics. Validated on load via [`SurgeConfig::validate`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurgeConfig {
    /// `surge.toml` schema version. Defaults to [`CONFIG_SCHEMA_VERSION`]
    /// when absent (existing configs predate the field). Frozen at 1 for
    /// v0.1; [`SurgeConfig::validate`] rejects any other value.
    #[serde(default = "default_config_schema_version")]
    pub schema_version: u32,
    #[serde(default = "default_default_agent")]
    pub default_agent: String,
    #[serde(default)]
    pub agents: HashMap<String, AgentConfig>,
    #[serde(default)]
    pub pipeline: PipelineConfig,
    #[serde(default)]
    pub routing: RoutingConfig,
    #[serde(default)]
    pub cleanup: CleanupPolicy,
    #[serde(default)]
    pub ide: IdeConfig,
    #[serde(default)]
    pub resilience: ResilienceConfig,
    #[serde(default)]
    pub log: LogConfig,
    #[serde(default)]
    pub analytics: AnalyticsConfig,
    /// Configured external task sources (Linear, GitHub Issues, ...).
    /// Empty by default — task-tracker integration is opt-in.
    #[serde(default)]
    pub task_sources: Vec<TaskSourceConfig>,
    /// Optional Telegram bot configuration. Absent → no TG bot loop.
    #[serde(default)]
    pub telegram: Option<TelegramConfig>,
    /// Inbox subsystem configuration (snooze poll interval, channels).
    #[serde(default)]
    pub inbox: InboxConfig,
    /// Project initialization and stable context defaults generated by `surge init`.
    #[serde(default)]
    pub init: InitConfig,
    /// Engine-level MCP (Model Context Protocol) servers that Surge spawns
    /// and exposes to every agent stage via `RoutingToolDispatcher`. Empty
    /// by default — MCP integration is opt-in. Each entry becomes one
    /// `surge_mcp::McpServerConnection`, registered for the duration of a
    /// run. Distinct from per-agent `AgentConfig::mcp_servers`, which the
    /// agent runtime spawns internally.
    #[serde(default)]
    pub mcp_servers: Vec<McpServerRef>,
    /// Engine-level guard against a node repeating an identical tool call,
    /// or running past a wall-clock budget, instead of burning the run's
    /// budget silently. Consumed by `surge_orchestrator::guard` via
    /// `RoutingToolDispatcher`. Conservative defaults when absent.
    #[serde(default)]
    pub tool_call_loop_guard: ToolCallLoopGuardConfig,
    /// Threshold beyond which a tool's output moves to the artifact store
    /// instead of flowing to the node in full. Consumed by
    /// `surge_orchestrator::spill`. Conservative default when absent.
    #[serde(default)]
    pub output_spill: OutputSpillConfig,
    /// Hard token budget for a memory-claims context pack, folded into the
    /// `project_memory` run seed by
    /// `surge_orchestrator::project_context::with_project_context_seed` via
    /// `surge_core::context_pack::ContextPack::build`
    /// (`.autopilot/competitive-waves/spec.md` §8, §23). Conservative
    /// default when absent.
    #[serde(default)]
    pub context_pack: ContextPackConfig,
    /// Blind-backoff duration and consecutive-blind-park escalation cap for
    /// `surge_core::capacity::CapacityPolicy` (Task 12, R37/R37.1/R38/R38.1).
    /// Conservative, visible defaults when absent — see
    /// `crate::capacity_config`.
    #[serde(default)]
    pub capacity: CapacityConfig,
    /// L3 (`surge:auto`) auto-merge gate configuration (spec §10/R31).
    #[serde(default)]
    pub merge_gate: MergeGateConfig,
    /// Where the extra attempt of an exhausted retry loop runs
    /// (`crate::escalation`). Unset: the stage's own agent.
    #[serde(default)]
    pub escalation: crate::escalation::EscalationConfig,
}

impl Default for SurgeConfig {
    fn default() -> Self {
        Self {
            schema_version: CONFIG_SCHEMA_VERSION,
            default_agent: "claude-acp".to_string(),
            agents: HashMap::new(),
            pipeline: PipelineConfig::default(),
            routing: RoutingConfig::default(),
            cleanup: CleanupPolicy::default(),
            ide: IdeConfig::default(),
            resilience: ResilienceConfig::default(),
            log: LogConfig::default(),
            analytics: AnalyticsConfig::default(),
            task_sources: Vec::new(),
            telegram: None,
            inbox: InboxConfig::default(),
            init: InitConfig::default(),
            mcp_servers: Vec::new(),
            tool_call_loop_guard: ToolCallLoopGuardConfig::default(),
            output_spill: OutputSpillConfig::default(),
            context_pack: ContextPackConfig::default(),
            capacity: CapacityConfig::default(),
            merge_gate: MergeGateConfig::default(),
            escalation: crate::escalation::EscalationConfig::default(),
        }
    }
}

mod agents;
mod init;
mod integrations;
mod io;
mod ops;
mod pipeline;
mod resilience;

pub use agents::*;
pub use init::*;
pub use integrations::*;
pub use ops::*;
use pipeline::default_true;
pub use pipeline::*;
pub use resilience::*;

#[cfg(test)]
mod schema_version_tests;
#[cfg(test)]
mod tests;
