//! Roadmap — description → roadmap → milestones → runs; the graph
//! decides the rest.
//!
//! Grounded in the real artifacts, in priority order:
//! - **PROJECT.MD card** — reads the actual `project.md` generated by
//!   `surge project describe` from the project root (the stable
//!   context seeded into every run).
//! - **THE LINE** — the default delivery pipeline rendered from the
//!   real bundled `linear-with-review` flow graph (nodes walked from
//!   `graph.start` along forward edges; human gates highlighted).
//! - **Milestones** — parsed from the project's `roadmap.toml`
//!   (`surge_core::roadmap::RoadmapArtifact`, the v2 ledger schema
//!   with per-task status/size/verified) when present; falls back to
//!   in-memory specs; labelled sample otherwise.
//!
//! "Amend roadmap" is a real workflow (`surge feature describe` →
//! roadmap-patch → approval) that runs through the engine; the header
//! points at it instead of faking an in-UI editor.

use gpui::*;
use gpui_component::StyledExt;
use surge_core::roadmap::{RoadmapArtifact, RoadmapStatus};
use surge_core::{BundledFlows, NodeKind};

use crate::app_state::AppState;
use crate::theme;
use crate::ui;

/// One chip on THE LINE.
struct LineStep {
    label: String,
    kind: NodeKind,
}

/// Milestone view-model (from roadmap.toml, specs, or sample).
#[derive(Clone)]
struct MilestoneRow {
    id: String,
    title: String,
    status_label: String,
    status_color: Hsla,
    desc: String,
    done: usize,
    total: usize,
    /// (task id, task title, dot color) chips.
    tasks: Vec<(String, String, Hsla)>,
    note: String,
}

fn status_parts(status: &RoadmapStatus) -> (&'static str, Hsla) {
    match status {
        RoadmapStatus::Pending => ("pending", theme::text_muted()),
        RoadmapStatus::Running => ("running", theme::accent()),
        RoadmapStatus::Paused => ("paused", theme::warning()),
        RoadmapStatus::ReadyForVerification => ("ready for verify", theme::warning()),
        RoadmapStatus::FailedVerification => ("failed verify", theme::error()),
        RoadmapStatus::Completed => ("completed", theme::success()),
        RoadmapStatus::Failed => ("failed", theme::error()),
        RoadmapStatus::Skipped => ("skipped", theme::text_muted()),
    }
}

/// Where the milestone data came from (shown honestly in the header).
#[derive(PartialEq, Clone, Copy)]
enum SourceKind {
    RoadmapToml,
    Specs,
    Sample,
}

pub struct RoadmapScreen {
    state: Entity<AppState>,
}

impl RoadmapScreen {
    pub fn new(state: Entity<AppState>, cx: &mut Context<Self>) -> Self {
        cx.observe(&state, |_this, _state, cx| cx.notify()).detach();
        Self { state }
    }

    /// Read `project.md` from the project root (or `.surge/`).
    fn project_md(&self, cx: &Context<Self>) -> Option<String> {
        let state = self.state.read(cx);
        let root = state.project_path.as_ref()?;
        for candidate in [root.join("project.md"), root.join(".surge/project.md")] {
            if let Ok(text) = std::fs::read_to_string(&candidate) {
                return Some(text);
            }
        }
        None
    }

    /// Parse the project's roadmap.toml when it exists.
    fn roadmap_artifact(&self, cx: &Context<Self>) -> Option<RoadmapArtifact> {
        let state = self.state.read(cx);
        let root = state.project_path.as_ref()?;
        for candidate in [root.join("roadmap.toml"), root.join(".surge/roadmap.toml")] {
            if let Ok(text) = std::fs::read_to_string(&candidate) {
                match toml::from_str::<RoadmapArtifact>(&text) {
                    Ok(artifact) => return Some(artifact),
                    Err(e) => {
                        tracing::warn!(path = %candidate.display(), "roadmap.toml parse failed: {e}");
                    },
                }
            }
        }
        None
    }

    fn milestones(&self, cx: &Context<Self>) -> (Vec<MilestoneRow>, SourceKind) {
        if let Some(artifact) = self.roadmap_artifact(cx) {
            let rows = artifact
                .milestones
                .iter()
                .map(|m| {
                    let total = m.tasks.len();
                    let done = m
                        .tasks
                        .iter()
                        .filter(|t| matches!(t.status, RoadmapStatus::Completed))
                        .count();
                    let (status_label, status_color) = status_parts(&m.status);
                    let tasks = m
                        .tasks
                        .iter()
                        .take(6)
                        .map(|t| {
                            let (_, color) = status_parts(&t.status);
                            let color = if t.verified { theme::success() } else { color };
                            (t.id.clone(), t.title.clone(), color)
                        })
                        .collect();
                    let sized: usize = m.tasks.iter().filter(|t| t.size.is_some()).count();
                    let verified = m.tasks.iter().filter(|t| t.verified).count();
                    MilestoneRow {
                        id: m.id.clone(),
                        title: m.title.clone(),
                        status_label: status_label.to_string(),
                        status_color,
                        desc: format!("{total} tasks · {sized} sized · {verified} verified"),
                        done,
                        total,
                        tasks,
                        note: String::new(),
                    }
                })
                .collect();
            return (rows, SourceKind::RoadmapToml);
        }

        let state = self.state.read(cx);
        if !state.specs.is_empty() {
            let rows = state
                .specs
                .iter()
                .map(|spec| {
                    let total = spec.subtasks.len();
                    let done = spec
                        .subtasks
                        .iter()
                        .filter(|s| {
                            matches!(s.execution.state, surge_core::spec::SubtaskState::Completed)
                        })
                        .count();
                    let tasks = spec
                        .subtasks
                        .iter()
                        .take(6)
                        .map(|s| {
                            let color = match s.execution.state {
                                surge_core::spec::SubtaskState::Completed => theme::success(),
                                surge_core::spec::SubtaskState::Running => theme::accent(),
                                surge_core::spec::SubtaskState::Failed => theme::error(),
                                _ => theme::text_muted(),
                            };
                            (s.id.to_string(), s.title.clone(), color)
                        })
                        .collect();
                    MilestoneRow {
                        id: spec.id.short().to_lowercase(),
                        title: spec.title.clone(),
                        status_label: format!("{:?}", spec.complexity).to_lowercase(),
                        status_color: theme::accent(),
                        desc: spec.description.chars().take(120).collect(),
                        done,
                        total,
                        tasks,
                        note: String::new(),
                    }
                })
                .collect();
            return (rows, SourceKind::Specs);
        }

        (sample_milestones(), SourceKind::Sample)
    }

    /// Walk the bundled linear-with-review flow from its start node
    /// along forward edges — the real default delivery pipeline.
    fn line_steps(&self) -> Vec<LineStep> {
        let Some(flow) = BundledFlows::by_name_latest("linear-with-review") else {
            return Vec::new();
        };
        let g = &flow.graph;
        let mut steps = Vec::new();
        let mut current = g.start.clone();
        let mut hops = 0;
        loop {
            let Some(node) = g.nodes.get(&current) else { break };
            steps.push(LineStep {
                label: current.as_str().replace('_', " "),
                kind: node.kind(),
            });
            hops += 1;
            if hops > 12 {
                break;
            }
            // First forward edge out of this node.
            let next = g
                .edges
                .iter()
                .find(|e| e.from.node == current)
                .map(|e| e.to.clone());
            match next {
                Some(n) if n != current => current = n,
                _ => break,
            }
        }
        steps
    }

    // ── panes ───────────────────────────────────────────────────────

    fn render_header(&self, source: SourceKind) -> Div {
        div()
            .h_flex()
            .gap(px(12.0))
            .items_center()
            .child(
                div()
                    .text_size(px(15.0))
                    .font_weight(FontWeight::BOLD)
                    .text_color(theme::text_primary())
                    .child("Roadmap"),
            )
            .child(ui::meta(
                "description → roadmap → milestones → runs — the graph decides the rest",
            ))
            .child(div().flex_1())
            .child(match source {
                SourceKind::RoadmapToml => ui::pill(
                    "roadmap.toml",
                    theme::success(),
                    theme::success().opacity(0.12),
                ),
                SourceKind::Specs => ui::pill(
                    "from specs",
                    theme::accent(),
                    theme::accent().opacity(0.12),
                ),
                SourceKind::Sample => ui::pill(
                    "sample · surge bootstrap writes the real one",
                    theme::text_muted(),
                    theme::panel_raised(),
                ),
            })
            .child(ui::meta("amend via `surge feature describe`"))
    }

    fn render_project_card(&self, cx: &Context<Self>) -> Div {
        let (body, is_real): (String, bool) = match self.project_md(cx) {
            Some(text) => {
                // Skip markdown headers; take the first paragraphs.
                let plain: String = text
                    .lines()
                    .filter(|l| !l.trim_start().starts_with('#'))
                    .collect::<Vec<_>>()
                    .join(" ");
                let head: String = plain.trim().chars().take(420).collect();
                (head, true)
            },
            None => (
                "No project.md yet — `surge project describe` scans the repo and \
                 writes the stable context that seeds every run."
                    .to_string(),
                false,
            ),
        };

        ui::panel()
            .v_flex()
            .gap(px(10.0))
            .p(px(15.0))
            .child(
                div()
                    .h_flex()
                    .gap(px(8.0))
                    .items_center()
                    .child(ui::section_label("PROJECT.MD · STABLE CONTEXT"))
                    .child(div().flex_1())
                    .child(ui::meta(if is_real {
                        "seeded into every run at start"
                    } else {
                        "surge project describe"
                    })),
            )
            .child(
                div()
                    .text_size(px(12.0))
                    .line_height(px(19.0))
                    .text_color(if is_real {
                        theme::text_primary().opacity(0.8)
                    } else {
                        theme::text_muted()
                    })
                    .child(body),
            )
    }

    fn render_line(&self) -> Div {
        let steps = self.line_steps();

        let mut row = div()
            .h_flex()
            .gap(px(7.0))
            .items_center()
            .flex_wrap()
            .child(
                div()
                    .text_size(px(9.0))
                    .font_weight(FontWeight::BOLD)
                    .text_color(theme::text_muted().opacity(0.85))
                    .mr(px(4.0))
                    .child("THE LINE"),
            );

        let n = steps.len();
        for (i, step) in steps.iter().enumerate() {
            let chip = match step.kind {
                NodeKind::HumanGate => div()
                    .h_flex()
                    .gap(px(5.0))
                    .items_center()
                    .px(px(9.0))
                    .py(px(3.0))
                    .rounded_md()
                    .bg(theme::accent().opacity(0.12))
                    .border_1()
                    .border_color(theme::accent().opacity(0.35))
                    .text_size(px(9.5))
                    .font_weight(FontWeight::BOLD)
                    .text_color(theme::accent())
                    .child(
                        div()
                            .w(px(7.0))
                            .h(px(7.0))
                            .rounded_sm()
                            .bg(theme::accent()),
                    )
                    .child(step.label.clone()),
                NodeKind::Terminal => div()
                    .px(px(9.0))
                    .py(px(3.0))
                    .rounded_md()
                    .bg(theme::success().opacity(0.12))
                    .border_1()
                    .border_color(theme::success().opacity(0.35))
                    .text_size(px(9.5))
                    .font_weight(FontWeight::BOLD)
                    .text_color(theme::success())
                    .child(format!("{} ✓", step.label)),
                _ => div()
                    .px(px(9.0))
                    .py(px(3.0))
                    .rounded_md()
                    .bg(theme::panel_raised())
                    .border_1()
                    .border_color(theme::hairline_strong())
                    .text_size(px(9.5))
                    .font_weight(FontWeight::SEMIBOLD)
                    .text_color(theme::text_primary().opacity(0.8))
                    .child(step.label.clone()),
            };
            row = row.child(chip);
            if i + 1 < n {
                row = row.child(
                    div()
                        .text_size(px(10.0))
                        .text_color(theme::text_muted().opacity(0.6))
                        .child("→"),
                );
            }
        }

        row = row.child(div().flex_1()).child(ui::meta("linear-with-review · bundled flow"));

        div()
            .h_flex()
            .px(px(14.0))
            .py(px(11.0))
            .rounded_lg()
            .bg(theme::panel())
            .border_1()
            .border_color(theme::hairline())
            .child(row)
    }

    fn render_milestone(&self, i: usize, m: &MilestoneRow) -> Div {
        let pct = if m.total > 0 {
            m.done as f32 / m.total as f32
        } else {
            0.0
        };

        let mut chips = div().h_flex().gap(px(8.0)).flex_wrap().items_center();
        for (id, title, color) in &m.tasks {
            let title_short: String = title.chars().take(34).collect();
            chips = chips.child(
                div()
                    .h_flex()
                    .gap(px(6.0))
                    .items_center()
                    .px(px(8.0))
                    .py(px(3.0))
                    .rounded_md()
                    .bg(theme::panel_deep())
                    .border_1()
                    .border_color(theme::hairline())
                    .child(ui::status_dot(*color))
                    .child(
                        div()
                            .text_size(px(9.5))
                            .font_weight(FontWeight::SEMIBOLD)
                            .text_color(theme::text_muted())
                            .child(id.clone()),
                    )
                    .child(
                        div()
                            .text_size(px(9.5))
                            .text_color(theme::text_primary().opacity(0.75))
                            .child(title_short),
                    ),
            );
        }
        if m.total > m.tasks.len() {
            chips = chips.child(ui::meta(format!("+{} more", m.total - m.tasks.len())));
        }
        if !m.note.is_empty() {
            chips = chips.child(ui::meta(m.note.clone()));
        }

        ui::panel()
            .h_flex()
            .gap(px(14.0))
            .p(px(15.0))
            .child(
                div()
                    .w(px(26.0))
                    .h(px(26.0))
                    .flex_shrink_0()
                    .rounded_md()
                    .bg(m.status_color.opacity(0.13))
                    .border_1()
                    .border_color(m.status_color.opacity(0.4))
                    .flex()
                    .items_center()
                    .justify_center()
                    .text_size(px(10.0))
                    .font_weight(FontWeight::BOLD)
                    .text_color(m.status_color)
                    .child(format!("{}", i + 1)),
            )
            .child(
                div()
                    .flex_1()
                    .min_w_0()
                    .v_flex()
                    .gap(px(8.0))
                    .child(
                        div()
                            .h_flex()
                            .gap(px(10.0))
                            .items_center()
                            .child(
                                div()
                                    .text_size(px(13.5))
                                    .font_weight(FontWeight::BOLD)
                                    .text_color(theme::text_primary())
                                    .child(m.title.clone()),
                            )
                            .child(ui::pill(
                                m.status_label.clone(),
                                m.status_color,
                                m.status_color.opacity(0.13),
                            ))
                            .child(div().flex_1())
                            .child(ui::meta(format!("{}/{} done", m.done, m.total))),
                    )
                    .child(
                        div()
                            .text_size(px(11.0))
                            .text_color(theme::text_muted())
                            .child(m.desc.clone()),
                    )
                    .child(
                        div()
                            .max_w(px(420.0))
                            .h(px(5.0))
                            .rounded_full()
                            .bg(theme::panel_deep())
                            .overflow_hidden()
                            .child(
                                div()
                                    .h_full()
                                    .rounded_full()
                                    .bg(m.status_color)
                                    .w(relative(pct.clamp(0.0, 1.0))),
                            ),
                    )
                    .child(chips),
            )
            .child(
                div()
                    .flex_shrink_0()
                    .v_flex()
                    .items_end()
                    .justify_center()
                    .gap(px(2.0))
                    .child(
                        div()
                            .text_size(px(16.0))
                            .font_weight(FontWeight::BOLD)
                            .text_color(if pct >= 1.0 {
                                theme::success()
                            } else {
                                theme::text_primary()
                            })
                            .child(format!("{:.0}%", pct * 100.0)),
                    )
                    .child(
                        div()
                            .text_size(px(9.0))
                            .text_color(theme::text_muted())
                            .child("done"),
                    ),
            )
    }
}

impl Render for RoadmapScreen {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let (milestones, source) = self.milestones(cx);

        let mut list = div().v_flex().gap(px(10.0));
        for (i, m) in milestones.iter().enumerate() {
            list = list.child(self.render_milestone(i, m));
        }

        div()
            .size_full()
            .id("roadmap-scroll")
            .overflow_y_scroll()
            .v_flex()
            .gap(px(14.0))
            .px(px(24.0))
            .pt(px(20.0))
            .pb(px(28.0))
            .bg(theme::panel_deep())
            .child(self.render_header(source))
            .child(self.render_project_card(cx))
            .child(self.render_line())
            .child(list)
    }
}

/// Labelled sample milestones (no roadmap.toml, no specs) — mirrors
/// the concept so the shape reads before `surge bootstrap` runs.
fn sample_milestones() -> Vec<MilestoneRow> {
    vec![
        MilestoneRow {
            id: "m1".into(),
            title: "Harden the intake path".into(),
            status_label: "completed".into(),
            status_color: theme::success(),
            desc: "4 tasks · 4 sized · 4 verified".into(),
            done: 4,
            total: 4,
            tasks: vec![
                ("m1-t1".into(), "OAuth token refresh".into(), theme::success()),
                ("m1-t2".into(), "Session cache".into(), theme::success()),
                ("m1-t3".into(), "Rate limiter middleware".into(), theme::success()),
                ("m1-t4".into(), "Audit log for logins".into(), theme::success()),
            ],
            note: String::new(),
        },
        MilestoneRow {
            id: "m2".into(),
            title: "Data import v2".into(),
            status_label: "running".into(),
            status_color: theme::accent(),
            desc: "5 tasks · 5 sized · 2 verified".into(),
            done: 2,
            total: 5,
            tasks: vec![
                ("m2-t1".into(), "Streaming CSV parser".into(), theme::success()),
                ("m2-t2".into(), "Schema inference".into(), theme::success()),
                ("m2-t3".into(), "Retry logic patch".into(), theme::accent()),
                ("m2-t4".into(), "Config loader refactor".into(), theme::error()),
                ("m2-t5".into(), "Import progress UI".into(), theme::text_muted()),
            ],
            note: "m2-t4 failed verification — routed back".into(),
        },
        MilestoneRow {
            id: "m3".into(),
            title: "Observability & cost controls".into(),
            status_label: "pending".into(),
            status_color: theme::text_muted(),
            desc: "3 tasks · 3 sized · 0 verified".into(),
            done: 0,
            total: 3,
            tasks: vec![
                ("m3-t1".into(), "Structured logging".into(), theme::text_muted()),
                ("m3-t2".into(), "Budget guard per run".into(), theme::text_muted()),
                ("m3-t3".into(), "Token usage dashboard".into(), theme::text_muted()),
            ],
            note: String::new(),
        },
    ]
}
